[package]
name = "gg"
version = "0.1.0"
authors = ["felix"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18"
ncollide2d = "0.20"
nphysics2d = "0.12"
ggez = "*"
mint = "*"
